"""empty message

Revision ID: 47c0c0b5f582
Revises: 2de5f182c2b4
Create Date: 2020-06-09 23:56:15.599082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c0c0b5f582'
down_revision = '2de5f182c2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sharing_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sharing_link')
    # ### end Alembic commands ###
