"""empty message

Revision ID: 66155c1cb20c
Revises: 900c17ebefe4
Create Date: 2020-06-07 03:23:27.961043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66155c1cb20c'
down_revision = '900c17ebefe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
