"""empty message

Revision ID: 715ab2d7605d
Revises: 
Create Date: 2020-06-05 01:33:30.114329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715ab2d7605d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
