"""empty message

Revision ID: 7c4bf19e5334
Revises: 9faf2acdf60b
Create Date: 2020-06-07 18:12:04.227501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4bf19e5334'
down_revision = '9faf2acdf60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###
